//
//  RegisterRouter.swift
//  SwiftArquiteturas
//
//  Created by Bruno Matos Silva on 02/11/23.
//  Copyright (c) 2023 ___ORGANIZATIONNAME___. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

@objc protocol RegisterRoutingLogic
{
    func routeToHome()
  //func routeToSomewhere(segue: UIStoryboardSegue?)
}

protocol RegisterDataPassing
{
  var dataStore: RegisterDataStore? { get }
}

class RegisterRouter: NSObject, RegisterRoutingLogic, RegisterDataPassing
{
  weak var viewController: RegisterViewController?
  var dataStore: RegisterDataStore?
  
  // MARK: Routing
  
    func routeToHome() {
        let destinationVC = HomeViewController()
        navigateToToModal(source: viewController!, destination: destinationVC)
    }

  // MARK: Navigation
  
    func navigateToPush(source: RegisterViewController, destination: UIViewController) {
        destination.modalPresentationStyle = .fullScreen
        source.navigationController?.pushViewController(destination, animated: true)
    }
  
  // MARK: Passing data
  
    func navigateToToModal(source: RegisterViewController, destination: UIViewController) {
        destination.modalPresentationStyle = .fullScreen
        source.navigationController?.present(destination, animated: true)
    }
}
