//
//  LoginRouter.swift
//  SwiftArquiteturas
//
//  Created by Bruno Matos Silva on 02/11/23.
//  Copyright (c) 2023 ___ORGANIZATIONNAME___. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

@objc protocol LoginRoutingLogic
{
    func routeToHome()
    func routeToRegister()
}

protocol LoginDataPassing
{
    var dataStore: LoginDataStore? { get }
}

class LoginRouter: NSObject, LoginRoutingLogic, LoginDataPassing
{
    
    // MARK: Routing
    func routeToHome() {
        let destinationVC = HomeViewController()
        navigateToToModal(source: viewController!, destination: destinationVC)
    }
    
    func routeToRegister() {
        let destinationVC = RegisterViewController()
        navigateToPush(source: viewController!, destination: destinationVC)
    }
    
    weak var viewController: LoginViewController?
    var dataStore: LoginDataStore?
    
    // MARK: Navigation
    func navigateToPush(source: LoginViewController, destination: UIViewController) {
        destination.modalPresentationStyle = .fullScreen
        source.navigationController?.pushViewController(destination, animated: true)
    }
    
    
    // MARK: Passing data
    func navigateToToModal(source: LoginViewController, destination: UIViewController) {
        destination.modalPresentationStyle = .fullScreen
        source.navigationController?.present(destination, animated: true)
    }
    
}
